version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9292:9292
    command: sh -c "npx prisma db push && npx prisma generate && npm run start"
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6*1FgC4GfbCAD1G1cBBFdg3ac12baGfB
      POSTGRES_DB: railway
      POSTGRES_HOST: monorail.proxy.rlwy.net
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 43344:5432

volumes:
  pgdata:
